name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy backend directory to EC2
        uses: appleboy/ssh-action@master
        with:
          host: "13.51.136.199"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git clone https://github.com/brizuelayeah/UNIZAR-30226-2024-10/backend.git /tmp/repository
            
