name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run a multi-line script
        run: |
            mkdir ../build
            cp -TR . ../build
            tar -cvf backend.tar ../build/dist/

      - name: Copy backend directory to EC2
        uses: appleboy/scp-action@master
        with:
          host: "13.51.136.199"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend.tar"
          target: "/home/ubuntu/backend"
