on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd home/backend
        
      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Install Vite globally
        run: npm install -g vite
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend
        
      - name: 📂 rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/home/
          remote_host: 13.51.136.199
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set ownership on remote server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
  
          # Create known_hosts file if it doesn't exist
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
            
          # Clear old key from known_hosts
          ssh-keygen -R 13.51.136.199 >> /home/runner/.ssh/known_hosts
  
          # Run the SSH command
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@13.51.136.199 \
          "sudo chown -R ec2-user:apache /var/www/html/backend/ && chmod 777 -R /var/www/html/home/backend/storage && chmod -R 777 /var/www/html/home/backend/bootstrap/cache/ && cd /var/www/html/home/backend/ && sudo npm install -g vite  && npm install && sudo chown -R ec2-user:apache /var/www/html/home/ && chmod +x /var/www/html/home/backend/dev_run.sh"          
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🎉 Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: 13.51.136.199
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/home/backend
            ./dev_run.sh
